# Generated by Django 3.2.6 on 2021-12-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0002_auto_20211219_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='text',
        ),
    ]
