# Generated by Django 3.2.6 on 2021-12-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0003_remove_event_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
