# Generated by Django 3.2.6 on 2022-01-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0005_alter_note_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
